// badwords.js
// Diccionario de palabras o fragmentos que no pueden aparecer en nombres ni clanes.
// Ponlas siempre en MINÚSCULAS. El script ya se encargará de comprobarlas sin importar mayúsculas/minúsculas.

export const forbiddenWords = [
    "asesinato", "asno", "bastardo", "bollera", "cabrón", "caca", "chupada", 
    "chupapollas", "chupetón", "concha", "concha de tu madre", "coño", 
    "coprofagía", "culo", "drogas", "esperma", "fiesta de salchichas", 
    "follador", "follar", "gilipichis", "gilipollas", "hacer una paja", 
    "haciendo el amor", "heroína", "hija de puta", "hijaputa", "hijo de puta", 
    "hijoputa", "idiota", "imbécil", "infierno", "jilipollas", "kapullo", 
    "lameculos", "maciza", "macizorra", "maldito", "mamada", "marica", 
    "maricón", "mariconazo", "martillo", "mierda", "nazi", "orina", "pedo", 
    "pendejo", "pervertido", "pezón", "pinche", "pis", "prostituta", "puta", 
    "racista", "ramera", "sádico", "semen", "sexo", "sexo oral", "soplagaitas", 
    "soplapollas", "tetas grandes", "tía buena", "travesti", "trio", "verga", 
    "vete a la mierda", "vulva", "2g1c", "2 girls 1 cup", "acrotomophilia", 
    "alabama hot pocket", "alaskan pipeline", "anal", "anilingus", "anus", 
    "apeshit", "arsehole", "ass", "asshole", "assmunch", "auto erotic", 
    "autoerotic", "babeland", "baby batter", "baby juice", "ball gag", 
    "ball gravy", "ball kicking", "ball licking", "ball sack", "ball sucking", 
    "bangbros", "bangbus", "bareback", "barely legal", "barenaked", "bastard", 
    "bastinado", "bbw", "bdsm", "beaner", "beaners", "beaver cleaver", 
    "beaver lips", "beastiality", "bestiality", "big black", "big breasts", 
    "big knockers", "big tits", "bimbos", "birdlock", "bitch", "bitches", 
    "black cock", "blonde action", "blonde on blonde action", "blowjob", 
    "blow job", "blow your load", "blue waffle", "blumpkin", "bollocks", 
    "bondage", "boner", "boob", "boobs", "booty call", "brown showers", 
    "brunette action", "bukkake", "bulldyke", "bullet vibe", "bullshit", 
    "bung hole", "bunghole", "busty", "butt", "buttcheeks", "butthole", 
    "camel toe", "camgirl", "camslut", "camwhore", "carpet muncher", 
    "carpetmuncher", "chocolate rosebuds", "cialis", "circlejerk", 
    "cleveland steamer", "clit", "clitoris", "clover clamps", "clusterfuck", 
    "cock", "cocks", "coprolagnia", "coprophilia", "cornhole", "coon", 
    "coons", "creampie", "cum", "cumming", "cumshot", "cumshots", 
    "cunnilingus", "cunt", "darkie", "date rape", "daterape", "deep throat", 
    "deepthroat", "dendrophilia", "dick", "dildo", "dingleberry", 
    "dingleberries", "dirty pillows", "dirty sanchez", "doggie style", 
    "doggiestyle", "doggy style", "doggystyle", "dog style", "dolcett", 
    "domination", "dominatrix", "dommes", "donkey punch", "double dong", 
    "double penetration", "dp action", "dry hump", "dvda", "eat my ass", 
    "ecchi", "ejaculation", "erotic", "erotism", "escort", "eunuch", "fag", 
    "faggot", "fecal", "felch", "fellatio", "feltch", "female squirting", 
    "femdom", "figging", "fingerbang", "fingering", "fisting", "foot fetish", 
    "footjob", "frotting", "fuck", "fuck buttons", "fuckin", "fucking", 
    "fucktards", "fudge packer", "fudgepacker", "futanari", "gangbang", 
    "gang bang", "gay sex", "genitals", "giant cock", "girl on", "girl on top", 
    "girls gone wild", "goatcx", "goatse", "god damn", "gokkun", 
    "golden shower", "goodpoop", "goo girl", "goregasm", "grope", "group sex", 
    "g-spot", "guro", "hand job", "handjob", "hard core", "hardcore", "hentai", 
    "homoerotic", "honkey", "hooker", "horny", "hot carl", "hot chick", 
    "how to kill", "how to murder", "huge fat", "humping", "incest", 
    "intercourse", "jack off", "jail bait", "jailbait", "jelly donut", 
    "jerk off", "jigaboo", "jiggaboo", "jiggerboo", "jizz", "juggs", "kike", 
    "kinbaku", "kinkster", "kinky", "knobbing", "leather restraint", 
    "leather straight jacket", "lemon party", "livesex", "lolita", 
    "lovemaking", "make me come", "male squirting", "masturbate", 
    "masturbating", "masturbation", "menage a trois", "milf", 
    "missionary position", "mong", "motherfucker", "mound of venus", 
    "mr hands", "muff diver", "muffdiving", "nambla", "nawashi", "negro", 
    "neonazi", "nigga", "nigger", "nig nog", "nimphomania", "nipple", 
    "nipples", "nsfw", "nsfw images", "nude", "nudity", "nutten", "nympho", 
    "nymphomania", "octopussy", "omorashi", "one cup two girls", 
    "one guy one jar", "orgasm", "orgy", "paedophile", "paki", "panties", 
    "panty", "pedobear", "pedophile", "pegging", "penis", "phone sex", 
    "piece of shit", "pikey", "pissing", "piss pig", "pisspig", "playboy", 
    "pleasure chest", "pole smoker", "ponyplay", "poof", "poon", "poontang", 
    "punany", "poop chute", "poopchute", "porn", "porno", "pornography", 
    "prince albert piercing", "pthc", "pubes", "pussy", "queaf", "queef", 
    "quim", "raghead", "raging boner", "rape", "raping", "rapist", "rectum", 
    "reverse cowgirl", "rimjob", "rimming", "rosy palm", 
    "rosy palm and her 5 sisters", "rusty trombone", "sadism", "santorum", 
    "scat", "schlong", "scissoring", "sexcam", "sexy", "sexual", "sexually", 
    "sexuality", "shaved beaver", "shaved pussy", "shemale", "shibari", "shit", 
    "shitblimp", "shitty", "shota", "shrimping", "skeet", "slanteye", "slut", 
    "s&m", "smut", "snatch", "snowballing", "sodomize", "sodomy", "spastic", 
    "spic", "splooge", "splooge moose", "spooge", "spread legs", "spunk", 
    "strap on", "strapon", "strappado", "strip club", "style doggy", "suck", 
    "sucks", "suicide girls", "sultry women", "swastika", "swinger", 
    "tainted love", "taste my", "tea bagging", "threesome", "throating", 
    "thumbzilla", "tied up", "tight white", "tit", "tits", "titties", "titty", 
    "tongue in a", "topless", "tosser", "towelhead", "tranny", "tribadism", 
    "tub girl", "tubgirl", "tushy", "twat", "twink", "twinkie", 
    "two girls one cup", "undressing", "upskirt", "urethra play", "urophilia", 
    "vagina", "venus mound", "viagra", "vibrator", "violet wand", 
    "vorarephilia", "voyeur", "voyeurweb", "voyuer", "wank", "wetback", 
    "wet dream", "white power", "whore", "worldsex", "wrapping men", 
    "wrinkled starfish", "xx", "xxx", "yaoi", "yellow showers", "yiffy", 
    "zoophilia", "🖕", "baiser", "bigornette", "bitte", "bloblos", "bordel", 
    "bourré", "bourrée", "brackmard", "branlage", "branler", "branlette", 
    "branleur", "branleuse", "brouter le cresson", "chatte", "chiasse", 
    "chier", "chiottes", "clito", "connard", "connasse", "conne", "couilles", 
    "cramouille", "déconne", "déconner", "emmerdant", "emmerder", "emmerdeur", 
    "emmerdeuse", "enculé", "enculée", "enculeur", "enculeurs", "enfoiré", 
    "enfoirée", "étron", "fille de pute", "fils de pute", "folle", "foutre", 
    "gerbe", "gerber", "gouine", "grande folle", "grogniasse", "gueule", 
    "jouir", "la putain de ta mère", "malpt", "ménage à trois", "merde", 
    "merdeuse", "merdeux", "meuf", "nègre", "nique ta mère", "nique ta race", 
    "palucher", "pédale", "pédé", "péter", "pipi", "pisser", "pouffiasse", 
    "pousse-crotte", "putain", "pute", "ramoner", "sac à foutre", "sac à merde", 
    "salaud", "salope", "suce", "tapette", "tanche", "teuch", "tringler", 
    "trique", "troncher", "trou du cul", "turlute", "zigounette",
    "admin", "administrator", "sistema", "system", "moderador", "bicifastness"
];

// Función para validar un texto contra el diccionario
export function containsBadWords(text) {
    if (!text) return false;
    const lowerText = text.toLowerCase();
    
    // Comprueba si alguna palabra prohibida está DENTRO del texto
    for (let word of forbiddenWords) {
        if (lowerText.includes(word)) {
            return true; // Contiene una palabra prohibida
        }
    }
    return false; // Está limpio
}